[package]
name = "ox_lang"
version = "0.1.0"
edition = "2024"

[dependencies]
miette = { version = "7", features = ["fancy"] }
thiserror = "1"
rand = "0.8.5"
lalrpop-util = "0.20.2"
regex = "1.10.4"

[build-dependencies]
lalrpop = "0.20.2"
